### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mmarquez** [JacksonTian/vue2js#1]
`/usr/local/lib/node_modules/vue2js/lib/index.js:70
    if (!this.state && this.tail.startsWith(templateStartPatt)) {

RangeError: Maximum call stack size exceeded
    at max (native)
    at String.startsWith (native)
    at Parser.template (/usr/local/lib/node_modules/vue2js/lib/index.js:70:34)
    at Parser.parse (/usr/local/lib/node_modules/vue2js/lib/index.js:123:10)
    at Parser.parse (/usr/local/lib/node_modules/vue2js/lib/index.js:128:12)
    at Parser.parse (/usr/local/lib/node_modules/vue2js/lib/index.js:128:12)
    at Parser.parse (/usr/local/lib/node_modules/vue2js/lib/index.js:128:12)
    at Parser.parse (/usr/local/lib/node_modules/vue2js/lib/index.js:128:12)
    at Parser.parse (/usr/local/lib/node_modules/vue2js/lib/index.js:128:12)
    at Parser.parse (/usr/local/lib/node_modules/vue2js/lib/index.js:128:12)
`

**Comment by JacksonTian** [comment]
提交一点测试代码吧。
